### ISSUE TITLE
Script doesn't work anymore

### ISSUE THREAD

**Issue by alexcampos09** [leerob/facebook-data-analyzer#4]
I believe this issue happened because Facebook likely changed parts of the format of the dump file (I'm assuming the dump file is the zip that I got when I downloaded my data).

**Comment by leerob** [comment]
Hey Alex! Thanks for reporting this. If you happen to figure out what changed, feel free to open a PR 😄

**Comment by leerob** [comment]
I ended up pulling down my Facebook data export again to see what had changed. Unfortunately, it's drastically different than when I first created this script. I've updated the README in case anyone is interested in trying to fix it 👍
